select nextval('movie_id_seq');
select currval('movie_id_seq');
select setval('movie_id_seq', 8079260);

create table toto.personnage(
	id_perso int 
		generated always as identity(
			start with 1
			increment by 10
		)
		constraint pk_personnage primary key,
	nom varchar(150) not null
); -- => sequence personnage_id_perso_seq
-- alternative: generated by default (+ souple)

insert into toto.personnage (nom) values ('toto')
	returning id_perso;

insert into toto.personnage (nom) values ('la maitresse')
	returning id_perso;

create sequence toto.ma_sequence;

create or replace function movie.title_year(title varchar, year smallint) returns varchar
as
$$
begin
	return title || ' (' || year || ')';
end;
$$ language plpgsql;

select 
	title_year(title, year)
from movie
where year = 1984;


SELECT * FROM pg_language;

-- Exemple de trigger:
-- logger chaque modification de la table movie: horodatage, qui et quel film

create table logs.log(
	id bigserial constraint pk_log primary key,
	username varchar(150) not null,
	when_action timestamp not null,
	movie_id int not null,
	action varchar(10) not null
);

-- fonction trigger
create or replace function movie.fn_log_movie_update() returns trigger
as $$
begin
	insert into logs.log (username, when_action, movie_id, action)
		values (current_user, CURRENT_TIMESTAMP::timestamp, NEW.id, 'INSERT');
	return new;
end;
$$ language plpgsql;

create or replace trigger trg_log_movie_update
after insert on movie.movie
for each row
execute function movie.fn_log_movie_update();

select 
	CURRENT_USER, 
	current_role, 
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP::timestamp -- i.e. without time zone / contraire: timestamptz 
	;














