-- user: movie, db : dbmovie

-- sequence + fonctions associées

select nextval('movie_id_seq');
select currval('movie_id_seq');
select setval('movie_id_seq', 8079260);

-- sequence + clause identity
create table toto.personnage(
	id_perso int 
		generated always as identity(
			start with 1
			increment by 10
		)
		constraint pk_personnage primary key,
	nom varchar(150) not null
); -- => sequence personnage_id_perso_seq
-- alternative: generated by default (+ souple)

insert into toto.personnage (nom) values ('toto')
	returning id_perso;

insert into toto.personnage (nom) values ('la maitresse')
	returning id_perso;

create sequence toto.ma_sequence;

create or replace function movie.title_year(title varchar, year smallint) returns varchar
as
$$
begin
	return title || ' (' || year || ')';
end;
$$ language plpgsql;

select 
	title_year(title, year)
from movie
where year = 1984;


SELECT * FROM pg_language;

-- Exemple de trigger:
-- logger chaque modification de la table movie: horodatage, qui et quel film

create table logs.log(
	id bigserial constraint pk_log primary key,
	username varchar(150) not null,
	when_action timestamp not null,
	movie_id int not null,
	action varchar(10) not null
);

-- fonction trigger
create or replace function movie.fn_log_movie_update() returns trigger
SECURITY DEFINER -- en tant que movie
as $$
declare
	v_movie_id int;
begin
	RAISE NOTICE 'Opération: %', TG_OP;
	if tg_op = 'DELETE' then
		v_movie_id = OLD.id;
	else
		v_movie_id = NEW.id;
	end if;
	insert into logs.log (username, when_action, movie_id, action)
		values (session_user, CURRENT_TIMESTAMP::timestamp, v_movie_id, TG_OP);
	return new;
end;
$$ language plpgsql;

create or replace trigger trg_log_movie_update
after insert or update or delete on movie.movie
for each row
execute function movie.fn_log_movie_update();

select 
	CURRENT_USER, 
	current_role, 
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP::timestamp -- i.e. without time zone / contraire: timestamptz 
	;

insert into movie (title, year) values ('Conjuring 2', 2025);

select * from log;

select * from movie where year = 2025;
update movie set duration = 128 where id = 8079264;
delete from movie where year = 2025;
select * from log;

select 
	id,
	TITLE,
	YeAr
from MoVie
where year = 2025;

create table toto."Lieu" (
	"id_lieu" serial,
	"Nom" varchar(150)
);

select * from lieu;
select * from Lieu;
select * from "Lieu";

-- vue simplifiée des tables
select * from pg_tables; 

-- vue détaillée: colonne relkind = type d'objet
--   table = 'r'
--   index = 'i'
--   sequence = 'S'
--   view = 'v'
select * from pg_class;

select distinct relkind from pg_class;
select * from pg_class where relkind = 'v';


select * 
from pg_class
where relowner = (
	select oid from pg_roles where rolname = 'movie'
)
order by relnamespace, relkind, relname;

select * 
from pg_class
where 
	relkind = 'r'
	and relowner = (
		select oid from pg_roles where rolname = 'movie'
	)
order by relnamespace, relkind, relname;

-- table movie: relfilenode=34050 
vacuum full movie;
-- table movie: relfilenode=34154 

-- table play :relfilenode = 34064, 3.4M
delete from play
where actor_id % 2 = 0;

vacuum play;
vacuum full play; -- NB: table verouillée
-- table play :relfilenode = 34162, 1.7M


-- comparer la taille des fichiers tables et indexes de la table movie
-- table movie ("34154"): 912K
-- index pk_movie ("34159"): 48K
-- index uniq_movie ("34160"): 64K

select * 
from pg_class
where 
	relkind in ('r', 'i')
	and relowner = (
		select oid from pg_roles where rolname = 'movie'
	)
order by relnamespace, relkind, relname;

-- apres suppression du fichier d'index pk_movie: 34159 
select * from movie where year = 1984;
-- ERROR:  could not open file "base/34038/34159": No such file or directory

select * from person limit 10;

reindex index pk_movie;
-- fichier d'index recréé: "34166"


select 4 + 34.2;
select 4 + 'toto';

select * 
from movie
where title like '%Terminator%';

select * 
from movie
where title ilike '%terminator%';

-- regexp POSIX
select *
from movie
where title ~* 'terminator [0-9]+';

select 
	current_time,
	current_date,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP::timestamp, -- i.e. without time zone / contraire: timestamptz 
	localtimestamp,
	CURRENT_TIMESTAMP::date
	;

show datestyle;

select *
from person
where birthdate between '1974-01-01' and '2034-12-31';

select *
from person
where birthdate between '01/02/1974' and '31/12/2034'
order by birthdate;

select *
from person
where birthdate between '01/02/1974'::date and '31/12/2034'::date
order by birthdate;

-- liste des collations
select *  from pg_collation;
select *  from pg_collation where collname like '%fr%';
show lc_time; -- "French_France.1252"

select 
	to_char(current_timestamp, 'TMday DD TMmonth YYYY HH24:MI:SS')
; -- "mardi 18 novembre 2025 15:04:49"

select
	name,
	birthdate,
	current_date - birthdate as delta_days,
	localtimestamp - birthdate::timestamp as delta_seconds,
	current_timestamp - '7 days 3 hours'::interval
from person
where name in (
	'Clint Eastwood',
	'James Cameron',
	'Arnold Schwarzenegger',
	'Grace Kelly'
);


select * from person
where extract(month from birthdate) = 10;

select * from person
where date_part('month', birthdate) = 10;

select name
from person
where name ~* '^r[eé]n[eé]'
order by name; -- collation fr

insert into toto.personnage (nom) values
	('mañana'),
	('matador'),
	('mano');

select * from personnage order by nom;

select *  from pg_collation where collname like '%es%';
select * from personnage order by nom COLLATE "es-ES-x-icu";








